modLoader="neoforge"
loaderVersion="[1,)" 

[[mods]]
modId="kubejscustomevents"
version="${file.jar.version}"
displayName="KubeJS CustomEvents"

[[dependencies.kubejscustomevents]]
modId="neoforge"
mandatory=true
versionRange="[47.0.0,)" # Versione di NeoForge
ordering="AFTER"
side="BOTH"

[[dependencies.kubejscustomevents]]
modId="kubejs"
mandatory=true # La tua mod richiede KubeJS per funzionare
versionRange="[2001.0.0,)" # Versione minima di KubeJS
ordering="AFTER" # Assicurati che KubeJS sia caricato prima del tuo addon
side="BOTH"